on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ssh-keyscan sinfin.de >> ~/.ssh/known_hosts
      - run: bash deploy.sh
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
